### ISSUE TITLE
Download the dataset

### ISSUE THREAD

**Issue by weizhenFrank** [joannetruong/robot-nav#1]
Hi I follow your instructions  to Download the 3D scenes, and get TOKEN_ID and TOKEN_SECRET from matterport.

But there's error:

(robot_nav) [wliu25@vector2 robot-nav]$ python -m habitat_sim.utils.datasets_download   --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET   --uids hm3d_train_v0.2   --data-path $DATA_DIR && python -m habitat_sim.utils.datasets_download   --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET   --uids hm3d_val_v0.2   --data-path $DATA_DIR 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    82    0    82    0     0    244      0 --:--:-- --:--:-- --:--:--   244
  0     0    0  8923    0     0  16163      0 --:--:-- --:--:-- --:--:-- 16163
Traceback (most recent call last):
  File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

Could you please take a look?

**Comment by hanzhi0410** [comment]
> Hi I follow your instructions to Download the 3D scenes, and get TOKEN_ID and TOKEN_SECRET from matterport.
> 
> But there's error:
> 
> (robot_nav) [wliu25@vector2 robot-nav]$ python -m habitat_sim.utils.datasets_download --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET --uids hm3d_train_v0.2 --data-path $DATA_DIR && python -m habitat_sim.utils.datasets_download --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET --uids hm3d_val_v0.2 --data-path $DATA_DIR % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 82 0 82 0 0 244 0 --:--:-- --:--:-- --:--:-- 244 0 0 0 8923 0 0 16163 0 --:--:-- --:--:-- --:--:-- 16163 Traceback (most recent call last): File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 772, in main(sys.argv[1:]) File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 766, in main download_and_place( File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 602, in download_and_place with tarfile.open(data_path + package_name, "r:*") as tar_ref: File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/tarfile.py", line 1797, in open raise ReadError("file could not be opened successfully") tarfile.ReadError: file could not be opened successfully
> 
> Could you please take a look?
> 
> 您好，我按照您的指示下载3D场景，并从matterport获取TOKEN_ID和TOKEN_SECRET。
> 
> 但有一个错误：
> 
> （robot_nav）[wliu25@vector2 robot-nav]$ python -m habitat_sim.utils.datasets_download --用户名$MATTERPORT_TOKEN_ID --密码$MATTERPORT_TOKEN_SECRET --uids hm3d_train_v0.2 --data-path $DATA_python -m habitat_sim.utils.datasets_download --用户名$MATTERPORT_TOKEN_ID --密码$MATTERPORT_TOKEN_SECRET --uids hm3d_val_v0.2 --data-path $DATA_DATA 总计百分比 %已接收% Xferd平均速度 时间 时间 时间电流 下载上传 总 花 左侧速度 100 82 0 82 0 0 244 0 --：--：-- 244 0 0 0 8923 0 0 16163 0 --：--：---：---：---：--：-- 16163 回溯（最近的呼叫最后一次）： 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/runpy.py“，第197行，in _run_module_as_main return _run_code（code，main_globals，None， 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/runpy.py“，第87行，in _run_code exec（code，run_globals） 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py”，第772行，在 main（sys.argv[1：]） File“/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py”，line 766，in main 下载_and_place（ 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py”，第602行，在download_and_place中 使用tarfile.open（data_path + package_name，“r：*”）作为tar_ref： 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/tarfile.py“，第1797行，打开 raise ReadError（“无法成功打开文件”） tarfile.ReadError：文件无法成功打开
> 
> 你能看一下吗？

Have you solved this problem

**Comment by xie-design** [comment]
> > Hi I follow your instructions to Download the 3D scenes, and get TOKEN_ID and TOKEN_SECRET from matterport.
> > But there's error:
> > (robot_nav) [wliu25@vector2 robot-nav]$ python -m habitat_sim.utils.datasets_download --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET --uids hm3d_train_v0.2 --data-path $DATA_DIR && python -m habitat_sim.utils.datasets_download --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET --uids hm3d_val_v0.2 --data-path $DATA_DIR % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 82 0 82 0 0 244 0 --:--:-- --:--:-- --:--:-- 244 0 0 0 8923 0 0 16163 0 --:--:-- --:--:-- --:--:-- 16163 Traceback (most recent call last): File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 772, in main(sys.argv[1:]) File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 766, in main download_and_place( File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 602, in download_and_place with tarfile.open(data_path + package_name, "r:*") as tar_ref: File "/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/tarfile.py", line 1797, in open raise ReadError("file could not be opened successfully") tarfile.ReadError: file could not be opened successfully
> > Could you please take a look?
> > 您好，我按照您的指示下载3D场景，并从matterport获取TOKEN_ID和TOKEN_SECRET。
> > 但有一个错误：
> > （robot_nav）[wliu25@vector2 robot-nav]$ python -m habitat_sim.utils.datasets_download --用户名$MATTERPORT_TOKEN_ID --密码$MATTERPORT_TOKEN_SECRET --uids hm3d_train_v0.2 --data-path $DATA_python -m habitat_sim.utils.datasets_download --用户名$MATTERPORT_TOKEN_ID --密码$MATTERPORT_TOKEN_SECRET --uids hm3d_val_v0.2 --data-path $DATA_DATA 总计百分比 %已接收% Xferd平均速度 时间 时间 时间电流 下载上传 总 花 左侧速度 100 82 0 82 0 0 244 0 --：--：-- 244 0 0 0 8923 0 0 16163 0 --：--：---：---：---：--：-- 16163 回溯（最近的呼叫最后一次）： 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/runpy.py“，第197行，in _run_module_as_main return _run_code（code，main_globals，None， 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/runpy.py“，第87行，in _run_code exec（code，run_globals） 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py”，第772行，在 main（sys.argv[1：]） File“/home/wliu25/miniconda3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py”，line 766，in main 下载_and_place（ 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/site-packages/habitat_sim-0.2.4-py3.9-linux-x86_64.egg/habitat_sim/utils/datasets_download.py”，第602行，在download_and_place中 使用tarfile.open（data_path + package_name，“r：*”）作为tar_ref： 文件“/home/wliu 25/miniconda 3/envs/robot_nav/lib/python3.9/tarfile.py“，第1797行，打开 raise ReadError（“无法成功打开文件”） tarfile.ReadError：文件无法成功打开
> > 你能看一下吗？
> 
> Have you solved this problem

Have you solved this problem?
